const app=document.querySelector('#app');
const key=d=>`week-notes:${iso(d)}`;
function iso(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10)}
function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function monday(d){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function label(d){const e=add(d,6);return `${d.getFullYear()} . ${d.getMonth()+1}.${d.getDate()} - ${e.getMonth()+1}.${e.getDate()}`}
function weekOnly(d){const e=add(d,6);return `${d.getMonth()+1}.${d.getDate()} - ${e.getMonth()+1}.${e.getDate()}`}
function data(d){let n={};try{n=JSON.parse(localStorage.getItem(key(d))||'{}')}catch(error){console.warn('Local storage is unavailable; entries will not persist.',error)}return {summary:'',privateBody:n.body||'',publicBody:'',drawing:'',drawingVisibility:'private',...n}}
function save(d,n){try{localStorage.setItem(key(d),JSON.stringify(n))}catch(error){console.warn('Could not save this entry locally.',error)}}
function weeks(year){const first=monday(new Date(year,0,4)),out=[];for(let d=first;d.getFullYear()<=year||add(d,6).getFullYear()===year;d=add(d,7))out.push(new Date(d));return out}
function escape(s=''){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function go(d){location.href=`?week=${iso(d)}`}
function home(){const now=new Date(),years=[];for(let y=now.getFullYear();y>=2024;y--)years.push(y);app.innerHTML=`<main class="book"><header class="masthead"><a class="wordmark" href="./">Je<span>Week</span>Summary</a><span class="edition">A personal annual record</span></header><section class="cover"><p class="kicker">Table of contents</p><h1>Weeks, kept<br>like chapters.</h1><p class="intro">A quiet archive for the things that happened, the things that mattered, and the stories you choose to share.</p><button class="jump" onclick="document.querySelector('.year-chapter').scrollIntoView({behavior:'smooth'})">Open the book</button></section><nav class="contents">${years.map(year=>`<section class="year-chapter"><header><span class="chapter-number">CHAPTER ${String(now.getFullYear()-year+1).padStart(2,'0')}</span><h2>${year}</h2><span class="year-count">${weeks(year).filter(w=>{const n=data(w);return n.summary||n.privateBody||n.publicBody}).length} written weeks</span></header><div class="chapters">${weeks(year).reverse().map((w,i)=>{const n=data(w);return `<button class="chapter" onclick="go(new Date('${iso(w)}T12:00:00'))"><span class="chapter-no">${String(weeks(year).length-i).padStart(2,'0')}</span><span class="chapter-date">${weekOnly(w)}</span><span class="chapter-summary">${n.summary||'Untitled week'}</span><span class="arrow">Read</span></button>`}).join('')}</div></section>`).join('')}</nav></main>`}
function toolbar(id){return `<div class="toolbar"><button data-c="bold" data-t="${id}"><b>B</b></button><button data-c="italic" data-t="${id}"><i>I</i></button><button data-c="insertUnorderedList" data-t="${id}">List</button></div>`}
function entry(d){const n=data(d);app.innerHTML=`<main class="entry-page"><header class="entry-nav"><a href="./" class="back">&#8592; Contents</a><a class="wordmark small" href="./">Je<span>Week</span>Summary</a><span id="status">Saved locally</span></header><section class="entry-title"><p class="kicker">CHAPTER / ${d.getFullYear()}</p><h1>${label(d)}</h1><input id="summary" value="${escape(n.summary)}" maxlength="180" placeholder="One sentence to remember this week" aria-label="Weekly summary"></section><section class="writing"><article class="writing-block private"><header><span>PRIVATE</span><h2>For your eyes</h2><p>Your unfiltered record. This content stays out of public exports.</p></header>${toolbar('private')}<div id="private" class="editor" contenteditable="true" data-placeholder="What really happened this week?">${n.privateBody}</div></article><article class="writing-block public"><header><span>PUBLIC</span><h2>For sharing</h2><p>The version you will be comfortable publishing or sending.</p></header>${toolbar('public')}<div id="public" class="editor" contenteditable="true" data-placeholder="What do you want to share?">${n.publicBody}</div></article></section><section class="ink"><header><div><p class="kicker">Handwriting</p><h2>Ink notes</h2></div><label>Visibility <select id="inkVisibility"><option value="private" ${n.drawingVisibility==='private'?'selected':''}>Private</option><option value="public" ${n.drawingVisibility==='public'?'selected':''}>Public</option></select></label><button id="clear">Clear</button></header><canvas id="canvas"></canvas><p>Stylus pressure changes the weight of each stroke. Touch and mouse use a steady line.</p></section><footer class="entry-actions"><button id="export">Export public .md</button><button class="primary" id="save">Save chapter</button></footer></main>`;bindEntry(d,n)}
function bindEntry(d,n){document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.t).focus();document.execCommand(b.dataset.c)});setCanvas(n.drawing);const persist=()=>{save(d,{summary:document.querySelector('#summary').value,privateBody:document.querySelector('#private').innerHTML,publicBody:document.querySelector('#public').innerHTML,drawing:document.querySelector('#canvas').toDataURL(),drawingVisibility:document.querySelector('#inkVisibility').value});document.querySelector('#status').textContent='Saved just now'};['summary','private','public','inkVisibility'].forEach(id=>document.querySelector('#'+id).oninput=persist);document.querySelector('#save').onclick=persist;document.querySelector('#clear').onclick=()=>{const c=document.querySelector('#canvas');c.getContext('2d').clearRect(0,0,c.width,c.height);persist()};document.querySelector('#export').onclick=()=>{const b=new Blob([`# ${label(d)}\n\n> ${document.querySelector('#summary').value}\n\n${document.querySelector('#public').innerText}`],{type:'text/markdown'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${iso(d)}-public.md`;a.click()}}
function setCanvas(src){const c=document.querySelector('#canvas'),ctx=c.getContext('2d'),r=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*r;c.height=h*r;ctx.scale(r,r);ctx.strokeStyle='#1c2c39';ctx.lineCap='round';if(src){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,w,h);img.src=src}let down=false,last;const pt=e=>{const box=c.getBoundingClientRect();return{x:e.clientX-box.left,y:e.clientY-box.top,p:Math.max(.14,e.pointerType==='pen'?e.pressure:.5)}};c.onpointerdown=e=>{down=true;last=pt(e);c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!down)return;const p=pt(e);ctx.beginPath();ctx.lineWidth=1+p.p*5.5;ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p};c.onpointerup=()=>{down=false;document.querySelector('#save').click()}}
const week=new URLSearchParams(location.search).get('week');week?entry(monday(new Date(`${week}T12:00:00`))):home();
