const app = document.querySelector('#app');
const DAY = 86400000;
let anchor = new Date();
let chosen = startOfWeek(new Date());
let drawing = false, last = null;
const key = d => `week-notes:${iso(d)}`;
const store = d => JSON.parse(localStorage.getItem(key(d)) || '{"summary":"","body":"","drawing":""}');
const save = (d, data) => localStorage.setItem(key(d), JSON.stringify(data));
function iso(d){ return new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10); }
function startOfWeek(d){ const x=new Date(d); x.setHours(0,0,0,0); x.setDate(x.getDate()-((x.getDay()+6)%7)); return x; }
function add(d,n){ const x=new Date(d); x.setDate(x.getDate()+n); return x; }
function fmt(d, short=false){ return d.toLocaleDateString('en-US',{month:'short',day:'numeric',...(short?{}:{year:'numeric'})}); }
function range(d){ const end=add(d,6); return `${d.getMonth()+1}.${d.getDate()}–${end.getMonth()+1}.${end.getDate()}`; }
function yearWeeks(d){ const start=startOfWeek(new Date(d.getFullYear(),0,4)); const weeks=[]; for(let w=new Date(start);w.getFullYear()<=d.getFullYear()||add(w,6).getFullYear()===d.getFullYear();w=add(w,7)) weeks.push(new Date(w)); return weeks; }
function render(){ const current = new Date(anchor.getFullYear(), anchor.getMonth(), 1), first=new Date(current); first.setDate(1-((first.getDay()+6)%7)); const monthName=current.toLocaleDateString('en-US',{month:'long',year:'numeric'}); const days=Array.from({length:42},(_,i)=>add(first,i)); const weeks=yearWeeks(chosen); const noteCount=weeks.filter(w=>{const n=store(w);return n.summary||n.body||n.drawing}).length; const record=store(chosen);
app.innerHTML=`<div class="shell"><header class="top"><div><div class="eyebrow">Personal weekly archive</div><div class="brand">Week Notes</div></div><button class="today" id="goToday">Jump to this week →</button></header><section class="grid"><section class="panel calendar"><div class="calendar-head"><h2>${monthName}</h2><div class="month-control"><button class="icon-btn" id="prev" aria-label="Previous month">‹</button><button class="icon-btn" id="next" aria-label="Next month">›</button></div></div><div class="weekdays"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div class="dates">${days.map(d=>{const w=startOfWeek(d), noted=store(w), cls=[d.getMonth()!==current.getMonth()?'outside':'',iso(w)===iso(chosen)?'selected':'',(noted.summary||noted.body||noted.drawing)?'has-note':''].join(' ');return `<button class="${cls}" data-day="${iso(d)}" aria-label="${fmt(d)}">${d.getDate()}</button>`}).join('')}</div></section><aside class="panel week-list"><h2>${chosen.getFullYear()} weeks</h2><p class="sub">${noteCount} saved week${noteCount===1?'':'s'} · Monday starts</p><div class="week-items">${weeks.map(w=>{const n=store(w), active=iso(w)===iso(chosen);return `<button class="week-item ${active?'active':''}" data-week="${iso(w)}"><span class="range">${range(w)}</span><span class="week-summary">${n.summary||'Add a one-sentence reflection'}</span></button>`}).join('')}</div></aside></section><section class="panel detail"><div class="detail-top"><div><div class="eyebrow">Weekly page</div><h1>${chosen.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</h1><p class="range-large">MON ${range(chosen).toUpperCase()}</p></div><span class="save-state" id="saved">Saved locally</span></div><div class="summary-field"><label for="summary">One-sentence summary</label><input id="summary" maxlength="180" placeholder="What defined this week?" value="${escapeHtml(record.summary)}"></div><div class="workspace"><div class="editor-wrap"><label>Your weekly entry</label><div class="tools"><button class="tool" data-command="bold"><b>B</b></button><button class="tool" data-command="italic"><i>I</i></button><button class="tool" data-command="insertUnorderedList">• List</button></div><article class="editor" id="editor" contenteditable="true" data-placeholder="Write freely — wins, lessons, links, small moments…">${record.body||''}</article></div><aside class="handwriting"><div class="canvas-header"><span class="canvas-title">Handwritten notes</span><button class="clear" id="clearDraw">Clear</button></div><canvas id="canvas" class="canvas"></canvas><p class="hand-tip">Draw with a mouse, finger, or stylus. It saves with this week.</p></aside></div><div class="footer-actions"><button class="button secondary" id="export">Export .md</button><button class="button" id="saveNow">Save week</button></div></section></div>`;
document.querySelector('#prev').onclick=()=>{anchor.setMonth(anchor.getMonth()-1);render()}; document.querySelector('#next').onclick=()=>{anchor.setMonth(anchor.getMonth()+1);render()}; document.querySelector('#goToday').onclick=()=>{chosen=startOfWeek(new Date());anchor=new Date();render()}; document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{chosen=startOfWeek(new Date(`${b.dataset.day}T12:00:00`));anchor=new Date(chosen);render()}); document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{chosen=new Date(`${b.dataset.week}T12:00:00`);anchor=new Date(chosen);render()});
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.command,false,null);document.querySelector('#editor').focus()}); setupCanvas(record.drawing); const persist=()=>{const c=document.querySelector('#canvas');save(chosen,{summary:document.querySelector('#summary').value,body:document.querySelector('#editor').innerHTML,drawing:c.toDataURL()});document.querySelector('#saved').textContent='Saved just now'}; document.querySelector('#summary').oninput=persist; document.querySelector('#editor').oninput=persist; document.querySelector('#saveNow').onclick=persist; document.querySelector('#clearDraw').onclick=()=>{clearCanvas();persist()}; document.querySelector('#export').onclick=exportMd;
}
function escapeHtml(s=''){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function setupCanvas(data){const c=document.querySelector('#canvas'),ctx=c.getContext('2d'),ratio=devicePixelRatio||1; c.width=c.clientWidth*ratio;c.height=c.clientHeight*ratio;ctx.scale(ratio,ratio);ctx.lineWidth=2;ctx.lineCap='round';ctx.strokeStyle='#24414a'; if(data){let image=new Image();image.onload=()=>ctx.drawImage(image,0,0,c.clientWidth,c.clientHeight);image.src=data} const point=e=>{const r=c.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top}}; c.onpointerdown=e=>{drawing=true;last=point(e);c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drawing)return;const p=point(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p};c.onpointerup=()=>{drawing=false;document.querySelector('#saveNow').click()};}
function clearCanvas(){const c=document.querySelector('#canvas');c.getContext('2d').clearRect(0,0,c.width,c.height)}
function exportMd(){const n=store(chosen), plain=document.querySelector('#editor').innerText;const blob=new Blob([`# Week of ${fmt(chosen)}\n\n> ${n.summary||'Weekly summary'}\n\n${plain}\n`],{type:'text/markdown'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`week-${iso(chosen)}.md`;a.click();URL.revokeObjectURL(a.href)}
render();
